### ISSUE TITLE
怎么会有这个错误？

### ISSUE THREAD

**Issue by goodforever** [z251257144/FireShop#2]
I/flutter (32075): CacheManager: Failed to download file from https://www.shengpinzhuang.com/static/upload/184729986e1c8854/5e0a842a094d1db5.jpg with error:
I/flutter (32075): SocketException: OS Error: Connection refused, errno = 111, address = www.shengpinzhuang.com, port = 47186
E/flutter (32075): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: SocketException: OS Error: Connection refused, errno = 111, address = www.shengpinzhuang.com, port = 47186
E/flutter (32075): null

**Comment by z251257144** [comment]
图片地址有问题，你换个图片

**Comment by goodforever** [comment]
这个图片https://www.shengpinzhuang.com是在源码哪里用的，我怎么查不到？

**Comment by z251257144** [comment]
工程里面没有使用这个网址，你加开源项目的QQ群吧，那里沟通快些

**Comment by goodforever** [comment]
我加了，这个群不存在，你公布的  QQ群：982449526

**Comment by z251257144** [comment]
你加我微信吧，z251257144
